version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: monthly
    day: tuesday
    time: '15:00'
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
    day: tuesday
    time: '15:00'
  groups:
    github-actions:
      patterns:
      - '*'
